package com.algorithmx.medicine101.data.models

import kotlinx.serialization.Serializable

/**
 * A definitive list of all content block types the AI can generate.
 */
enum class BlockType {
    TEXT,       // A standard paragraph of text
    HEADER,     // A section heading
    LIST,       // A bulleted or numbered list
    CALLOUT,    // An emphasized block of text (like a warning or tip)
    TABLE,      // A markdown table
    IMAGE,      // A placeholder for an image (content would be a description)
    YOUTUBE,    // A YouTube video embed (content would be the URL)
    ACCORDION,  // A collapsible section (content could be Title;Details)
    DROPDOWN,   // A dropdown menu
    CODE        // A block of formatted code
}

/**
 * Represents a single block of content as generated by the AI.
 */
@Serializable
data class AiGeneratedBlock(
    val type: String,
    val content: String
)

/**
 * Contextual information about a note for AI generation.
 */
data class NoteContext(
    val noteTitle: String,
    val noteCategory: String,
    val parentNoteTitle: String? = null,
    val existingContentSummary: String? = null
)
